[package]
name = "filend"
version = "0.1.0"
authors = ["hgonomeg <hgonomeg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
preferences = "1.1"
actix-web = "3"
[dependencies.gtk]
version = "0.9"
features = ["v3_16"]
[dependencies.gio]
version = ""
features = ["v2_44"]
