[package]
name = "filend"
version = "0.3.0-alpha"
authors = ["hgonomeg <hgonomeg@gmail.com>"]
edition = "2021"

[dependencies]
preferences = { git = "https://github.com/andybarron/preferences-rs" }
actix-web = "4"
actix-rt = "2"
actix-files = "0.6"
serde = "1"
serde_derive = "1"
rand = "0.8"
